= 1-ElectronicsToAtomistics
As mentioned previously, each bridge will contain homogeneous file structures for intuitive navigation from the command line.



== Files
.`./evfit.f`
Fortran file for fitting a curve to the electron energy (units of eV) for varying lattice parameter (units of Angstrom) separation between electrons.
This compiles out to `./evfit` which is, in turn, called by `./ev_curve`.

.`./ev_curve`
Accepts two positional arguments: reference structure, and initial guess for lattice parameter.
For some range around the initial guess for lattice parameter, uses Quantum Espresso to calculate the electronic energy at the lattice parameter separation with other settings according to the associated `<reference structure>.ev.in` file.
Will print to terminal and summary files the electronic energy for each lattice parameter (`EvsA`) and cell volume (`EvsV`) and the equilibrium electronic energy, lattice parameter, and bulk modulus.

.`./EvA_EvV_plot.jl` / `./EvA_EvV_plot.py`
Whether using the Julia or Python file, the output `EvsA` and `EvsV` files from `./ev_curve` are plotted for electronic energy against lattice parameter and cell volume, respectively.
Creates a plot for each and a plot grid for comparison.
Can use some offset value (assigned to `energy_offset`) to subtract the background energy associated with the electron cloud with a sufficiently large lattice parameter so that electronic energy is initially positive before becoming negative.

.`./gsfe_curve.jl` / `./gsfe_curve.py`
Calculates the generalized stacking fault energy (GSFE) curve according to three positional arguments: reference structure, lattice parameter, and slip direction.
This was originally written in Python 2, but the Julia version of this script leverages parallel processing to calculate within a human lifetime.
If on a single-core processor or using Python, then use `./OutputFileCreator.<ext>` to create the inputs necessary to submit a job on Rescale.

.`./OutputFileCreator.jl` / .`./OutputFileCreator.py`
Almost an exact copy of `./gsfe_curve.<ext>`, but skips the calculation step in lieu of writing the inputs to an external file: `gsfe_<X>.in`.
Creates the number of input files according to the number of data points desired in the resulting GSFE curve.

.`./OutputFileSummarizer.jl` / .`./OutputFileSummarizer.py`
Almost an exact copy of `./gsfe_curve.<ext>`, but skips the calculation step in lieu of processing the `gsfe_<X>.out` files.

.`./rescale_commands.sh`
Command script that gets uploaded to Rescale to calculate all the `./gsfe_<X>.in` files.
Note that the number of processors used in the `mpirun` call should be less than or equal to the number of cores of the Rescale job.



== Calculations
This length scale requires the use of pseudopotential files as input to Quantum Espresso to dictate how electronic energies are calculated.
Visit any of the following for a pseudopotential file of choice:

. https://pseudopotentiallibrary.org
. http://www.physics.rutgers.edu/gbrv/#Fe
. https://www.materialscloud.org/discover/sssp/table/efficiency
. https://www.materialscloud.org/discover/sssp/table/precision

Place the desired pseudopotential file into `~/1-ElectronicsToAtomistics/Calculations/`: all scripts contained herein reference this pseudopotential file.


=== Energy Offset
include::./energy_offset.adoc[]


=== K-Point Study
include::./kpoint_study.adoc[]


=== GSFE Curve
include::./gsfe_curve.adoc[]