// document metadata
= Integrated Computational Materials Engineering
Joby M. Anthony III <jmanthony1@liberty.edu>
:affiliation: Ph. D. Candidate
:document_version: 2.0
:revdate: February 20, 2025
:description: Scripts necessary to bridge certain length scales of Integrated Computational Materials Engineering design process.
:keywords: multi-scale modeling, shell scripting, WSL, Python, Julia, parallel processing
:imagesdir: {docdir}/images
:bibtex-file: references.bib
:toc: auto
:xrefstyle: short
:sectnums: |,all|
:chapter-refsig: Chap.
:section-refsig: Sec.
:stem: latexmath
:eqnums: AMS
// :stylesdir: {docdir}
// :stylesheet: asme.css
// :noheader:
// :nofooter:
// :docinfodir: {docdir}
// :docinfo: private
:front-matter: any
:!last-update-label:

// example variable
// :fn-1: footnote:[]
// end document metadata





// begin document
[abstract]
.Abstract
Instructions to install Linux codes for Liberty University School of Engineering course ENGR 851: Integrated Computational Materials Engineering.
If host operating system is Windows, then use the Windows Subsystem for Linux (WSL) to install Ubuntu 20.04.
[.underline]#This does not currently install the MATLAB tools MPCv4 nor DMGfit.#
The folders `1-ElectronicsToAtomistics`, `2-AtomisticsToDislocationMobility`, and `3-DislocationMobilityToCrystalPlasticity` each represent the first three bridges from lower length scales up to the continuum length scale and have similar, local file structures for homogeneous navigation at the Linux terminal.
The `setup.sh` script under each bridge has, at the top, user-defined variables to control the installation of codes and scripts and build the infrastructure to work at those length scales.
By default, the repository-level `setup.sh` (next to the README), executes each bridge-level `setup.sh` script with the user-defined variables at the top of those scripts.
To modify the installation of each bridge, then modify the appropriate user-defined variables and either run the bridge-level `setup.sh` as desired or execute the repository-level `setup.sh`.

*Keywords:* _{keywords}_



[#sec-install, {counter:secs}]
== Installation
:!subs:
:!figs:
:!tabs:

If host machine is Debian-based distro, then skip ahead to....
Otherwise, if Windows 10/11, then either setup WSL or setup a https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html[virtual (guest) machine] (VMware Workstation 16 Player) with an https://ubuntu.com/download/desktop[Ubuntu Desktop] or use https://docs.microsoft.com/en-us/windows/wsl/install[Windows Subsystem for Linux].
Afterward, clone this repository `git clone https://github.com/jmanthony3/ICME.git` wherever desired inside the Linux distribution.

If setting up WSL, then make sure that both "Virtual Machine Platform" and "Windows Subsystem for Linux" are checked.
After restarting the machine, execute `wsl --install -d Ubuntu` from a command terminal.



[#sec-bridges, {counter:secs}]
== Length-Scale Bridges
Each of the bridges has a `./setup.sh` script for installing the code infrastructure necessary to build that ICME bridge.
The following sections describe the user-defined variables for their own `setup.sh` script.
By default, the repository-level `~/.setup.sh` will execute the `setup.sh` script of each bridge with the currently defined user-defined variables.
The most important variable belongs to bridges (1) and (2): `COMPUTING_LANGUAGE`.
By default, `COMPUTING_LANGUAGE="Julia"` will install the latest version of https://julialang.org[Julia] and the appropriate packages.
Most calculations are controlled from Linux bash scripts, but some auxiliary calculations and plots are performed and created by Python or Julia scripts.

As mentioned previously, each bridge will contain homogeneous file structures for intuitive navigation from the command line.
Each bridge contains two primary folders: `~/<bridge>/Files/` and `~/<bridge>/Calculations/`.
Any file necessary to install the infrastructure for a bridge is placed into the `~/<bridge>/Files/` folder.
The `~/<bridge>/Calculations/` folder contains all the work for building that bridge.
The scripts necessary to build this bridge are copied from the `~/<bridge>/Files/` folder into the `~/<bridge>/Calculations/0-Scripts/` folder: this allows for user edits for individual calculations and preserves an original for reference.
Each `~/<bridge>/Calculation/` folder contains a `/0-Scripts/` folder for the scripts pertinent to that bridge for calculating locally or uploading to Rescale.


[#sec-bridge-electrons_to_atoms, {counter:sec-sub}]
=== Bridging Electronics to Atomistics
:!subs:
:!figs:
:!tabs:

Go link:src/1-ElectronicsToAtomistics/index.html[here] for building this bridge.
The following snippet shows the default values for the user-defined variables that controls the install.

[source, bash]
----
include::./../1-ElectronicsToAtomistics/setup.sh[lines=1..22]
----

To use some version of Quantum Espresso, get the tarball of the desired https://github.com/QEF/q-e/releases[flavor] and put into `~/1-ElectronicsToAtomistics/Files/`.
In the `setup.sh` script, `QUANTUM_ESPRESSO_INSTALL_LOC` and `QUANTUM_ESPRESSO_VERSION` specifies the install directory and version, respectively.
[IMPORTANT]
====
`QUANTUM_ESPRESSO_VERSION` must be a string that is the full name of the tarball of choice minus the `.tar.gz` extension.
For example, Quantum Espresso v6.0.0 is installed from the `qe-6.0.0.tar.gz` tarball and specified by `QUANTUM_ESPRESSO_VERSION="qe-6.0.0"`.
====
Some later scripts can leverage multiple threads for parallel processing; therefore, the `NUM_PROCS` variable will, by default, grab all the available threads on the machine (recommended).
The `UNDER_PROC` variable was inspired the work of Reid Prichard for under-subscription in parallel environments cite:[prichardNOVELHPCSCALING2022].
Whether this variable is actually needed has yet to be determined.

To install the Quantum Espresso environment, navigate to the directory of and execute the `~/1-ElectronicsToAtomistics/setup.sh` bash script.
Regardless of existing packages on guest machine, this script will `./configure` and `make` the desired flavor of Quantum Espresso; update the `$PATH` environment variable; and, perform tests to, hopefully, demonstrate success of installing the Linux environment and the ability to execute scripts.
These tests also depend on whether `COMPUTING_LANGUAGE` is set to `"Julia"` (recommended) or `"Python"`.

// . https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm200[Input description]
// . https://icme.hpc.msstate.edu/mediawiki/index.php/EvA_EvV_plot.py.html[`EvA_EvV_plot.py`]
// . https://icme.hpc.msstate.edu/mediawiki/index.php/Convergence_plots.py.html[`Convergence_plots.py`]
// . https://icme.hpc.msstate.edu/mediawiki/index.php/EOS_plot.py.html[`EOS_plot.py`]
// . https://icme.hpc.msstate.edu/mediawiki/index.php/EOS_comp_plot.py.html[`EOS_comp_plot.py`]
// . https://icme.hpc.msstate.edu/mediawiki/index.php/Ecut_conv.py.html[`Ecut_conv.py`]




[#sec-bridge-dislocation_mobility, {counter:sec-sub}]
=== Bridging Atomistics to Dislocation Mobility
:!subs:
:!figs:
:!tabs:

// https://www.ovito.org/linux-downloads/
// https://gist.github.com/sakethramanujam/faf5b677b6505437dbdd82170ac55322

Go link:src/2-AtomisticsToDislocationMobility/index.html[here] for building this bridge.
The following snippet shows the default values for the user-defined variables that controls the install.

[source, bash]
----
include::./../2-AtomisticsToDislocationMobility/setup.sh[lines=1..24]
----



[#sec-bridge-crystal_plasticity, {counter:sec-sub}]
=== Bridging Dislocation Mobility to Crystal Plasticity
:!subs:
:!figs:
:!tabs:

Go link:src/3-DislocationMobilityToCrystalPlasticity/index.html[here] for building this bridge.
The following snippet shows the default values for the user-defined variables that controls the install.

[source, bash]
----
include::./../3-DislocationMobilityToCrystalPlasticity/setup.sh[lines=1..14]
----



// [appendix#sec-appendix-Figures]
// == Figures



[bibliography]
== References
bibliography::[]
// end document





// that's all folks 