name: Documentation

on:
  push:
    branches: main
    tags: '*'
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.3"]
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install gems
      run: gem install asciidoctor asciidoctor-bibtex
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install asciidoxy
    - name: Build docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
      # run: asciidoxy --image-dir={image_dir} --build-dir={buildPath} --destination-dir={adocPath} --cache-dir={cachePath} --multipage --require=asciidoctor-bibtex --require=asciidoctor-pdf filename
      run: asciidoxy --base-dir=docs/src --destination-dir=docs/build --cache-dir=docs/cache --multipage --require=asciidoctor-bibtex docs/src/index.adoc
